//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class T_Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Members()
        {
            this.T_ShippingDetails = new HashSet<T_ShippingDetails>();
        }

        public int MemberId { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please Enter Name..!")]
        [Remote("Register", "Home", HttpMethod = "POST", ErrorMessage = "Last Name Address Already Register")]
        public string FirstName { get; set; }



        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Enter last Name")]
        [Remote("Register", "Home", HttpMethod = "POST", ErrorMessage = "Last Name Address Already Register")]
        public string LastName { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please Enter Email Address")]
        [RegularExpression(@"\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w{2,4}([-.]\w{2,4})*([,;]\s*\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w{2,4}([-.]\w{2,4})*)*", ErrorMessage = "Invalid Email Format...!")]
        [Remote("Register", "Home", HttpMethod = "POST", ErrorMessage = "Email Address Already Register")]
        public string EmailId { get; set; }


        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please Enter Password...!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ShippingDetails> T_ShippingDetails { get; set; }
    }
}
